spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bermali
    username: eren
    password: 123
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres

  algorithm:
    key: ${algorithm_key}