version: '3.9'

services:
  db:
    image: postgres:16
    container_name: PostGresDB
    environment:
      POSTGRES_NAME: eren
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bermali
    volumes:
      - database:/var/lib/postgres/data
    ports:
      - "5432:5432"

volumes:
  database: